/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    locations: Location;
    'events-weekly': EventsWeekly;
    'events-upcoming': EventsUpcoming;
    deals: Deal;
    campaigns: Campaign;
    forms: Form;
    leads: Lead;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'events-weekly': EventsWeeklySelect<false> | EventsWeeklySelect<true>;
    'events-upcoming': EventsUpcomingSelect<false> | EventsUpcomingSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'settings-seo': SettingsSeo;
    'settings-tracking': SettingsTracking;
    'settings-integrations': SettingsIntegration;
    'settings-brand': SettingsBrand;
  };
  globalsSelect: {
    'settings-seo': SettingsSeoSelect<false> | SettingsSeoSelect<true>;
    'settings-tracking': SettingsTrackingSelect<false> | SettingsTrackingSelect<true>;
    'settings-integrations': SettingsIntegrationsSelect<false> | SettingsIntegrationsSelect<true>;
    'settings-brand': SettingsBrandSelect<false> | SettingsBrandSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType?: ('brand' | 'location' | 'landing' | 'default') | null;
  layout?:
    | (
        | {
            headline: string;
            subline?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            mode: 'auto' | 'manual';
            deal?: (number | null) | Deal;
            showOn?: ('header' | 'burger' | 'section') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dealSlot';
          }
        | {
            campaign?: (number | null) | Campaign;
            renderMode?: ('popup' | 'floating_bar') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campaignSlot';
          }
        | {
            titleOverride?: string | null;
            locationSlug?: string | null;
            highlightToday?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'weeklyEvents';
          }
        | {
            titleOverride?: string | null;
            locationSlug?: string | null;
            highlightOnly?: boolean | null;
            maxItems?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'upcomingEvents';
          }
        | {
            form: number | Form;
            titleOverride?: string | null;
            layout?: ('default' | 'compact' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formEmbed';
          }
        | {
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            images?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  /**
   * Transition field: stores current custom content JSON for CI-safe migration.
   */
  legacyContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
    jsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  label?: string | null;
  shortText?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  image?: (number | null) | Media;
  startAt?: string | null;
  endAt?: string | null;
  priority?: number | null;
  placement?: {
    globalHeader?: boolean | null;
    globalBurger?: boolean | null;
    pages?: (number | Page)[] | null;
    locations?: (number | Location)[] | null;
  };
  deviceTargeting?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  address?: string | null;
  city?: string | null;
  phone?: string | null;
  email?: string | null;
  geo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  openingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?: string | null;
  images?: (number | Media)[] | null;
  seo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  type: 'popup' | 'floating_bar';
  headline: string;
  text?: string | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  targeting?: {
    includePages?: (number | Page)[] | null;
    excludePages?: (number | Page)[] | null;
    locations?: (number | Location)[] | null;
    device?: ('all' | 'desktop' | 'mobile') | null;
  };
  timing?: {
    startAt?: string | null;
    endAt?: string | null;
    trigger?: ('delay' | 'scroll' | 'exit_intent') | null;
    triggerValue?: number | null;
    frequency?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  slug: string;
  status?: ('draft' | 'published' | 'archived') | null;
  fields?:
    | {
        name: string;
        label: string;
        type:
          | 'text'
          | 'textarea'
          | 'email'
          | 'phone'
          | 'number'
          | 'dropdown'
          | 'checkbox'
          | 'radio'
          | 'date'
          | 'time'
          | 'hidden'
          | 'consent';
        required?: boolean | null;
        options?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        validation?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  targetPages?: (number | Page)[] | null;
  recipientEmail?: string | null;
  webhookUrl?: string | null;
  zendeskMode?: ('none' | 'email' | 'webhook') | null;
  prevoEnabled?: boolean | null;
  prevoTag?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-weekly".
 */
export interface EventsWeekly {
  id: number;
  title: string;
  slug: string;
  descriptionShort?: string | null;
  descriptionLong?: string | null;
  weekdays?: ('wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  startTime?: string | null;
  endTime?: string | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  sortOrder?: number | null;
  locations?: (number | Location)[] | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-upcoming".
 */
export interface EventsUpcoming {
  id: number;
  title: string;
  slug: string;
  startDateTime: string;
  endDateTime?: string | null;
  locations?: (number | Location)[] | null;
  description?: string | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  highlight?: boolean | null;
  priority?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  seo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  formSlug?: string | null;
  email?: string | null;
  name?: string | null;
  phone?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'open' | 'done') | null;
  integrationLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'events-weekly';
        value: number | EventsWeekly;
      } | null)
    | ({
        relationTo: 'events-upcoming';
        value: number | EventsUpcoming;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subline?: T;
              backgroundImage?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        dealSlot?:
          | T
          | {
              mode?: T;
              deal?: T;
              showOn?: T;
              id?: T;
              blockName?: T;
            };
        campaignSlot?:
          | T
          | {
              campaign?: T;
              renderMode?: T;
              id?: T;
              blockName?: T;
            };
        weeklyEvents?:
          | T
          | {
              titleOverride?: T;
              locationSlug?: T;
              highlightToday?: T;
              id?: T;
              blockName?: T;
            };
        upcomingEvents?:
          | T
          | {
              titleOverride?: T;
              locationSlug?: T;
              highlightOnly?: T;
              maxItems?: T;
              id?: T;
              blockName?: T;
            };
        formEmbed?:
          | T
          | {
              form?: T;
              titleOverride?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
      };
  legacyContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        ogImage?: T;
        noindex?: T;
        jsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  city?: T;
  phone?: T;
  email?: T;
  geo?: T;
  openingHours?: T;
  description?: T;
  images?: T;
  seo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-weekly_select".
 */
export interface EventsWeeklySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  descriptionShort?: T;
  descriptionLong?: T;
  weekdays?: T;
  startTime?: T;
  endTime?: T;
  image?: T;
  ctaLabel?: T;
  ctaLink?: T;
  sortOrder?: T;
  locations?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-upcoming_select".
 */
export interface EventsUpcomingSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDateTime?: T;
  endDateTime?: T;
  locations?: T;
  description?: T;
  image?: T;
  ctaLabel?: T;
  ctaLink?: T;
  highlight?: T;
  priority?: T;
  status?: T;
  seo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  shortText?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  image?: T;
  startAt?: T;
  endAt?: T;
  priority?: T;
  placement?:
    | T
    | {
        globalHeader?: T;
        globalBurger?: T;
        pages?: T;
        locations?: T;
      };
  deviceTargeting?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  type?: T;
  headline?: T;
  text?: T;
  image?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  targeting?:
    | T
    | {
        includePages?: T;
        excludePages?: T;
        locations?: T;
        device?: T;
      };
  timing?:
    | T
    | {
        startAt?: T;
        endAt?: T;
        trigger?: T;
        triggerValue?: T;
        frequency?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        required?: T;
        options?: T;
        validation?: T;
        id?: T;
      };
  targetPages?: T;
  recipientEmail?: T;
  webhookUrl?: T;
  zendeskMode?: T;
  prevoEnabled?: T;
  prevoTag?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  formSlug?: T;
  email?: T;
  name?: T;
  phone?: T;
  payload?: T;
  utm?: T;
  consent?: T;
  status?: T;
  integrationLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-seo".
 */
export interface SettingsSeo {
  id: number;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  robots?: string | null;
  sitemapEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-tracking".
 */
export interface SettingsTracking {
  id: number;
  ga4MeasurementId?: string | null;
  metaPixelId?: string | null;
  otherScripts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-integrations".
 */
export interface SettingsIntegration {
  id: number;
  zendesk?: {
    inboundEmail?: string | null;
    webhookUrl?: string | null;
  };
  prevo?: {
    apiUrl?: string | null;
    apiKey?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-brand".
 */
export interface SettingsBrand {
  id: number;
  header?: {
    menuItems?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  footer?: {
    logoText?: string | null;
    text?: string | null;
    links?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  brand?: {
    name?: string | null;
    locations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-seo_select".
 */
export interface SettingsSeoSelect<T extends boolean = true> {
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  robots?: T;
  sitemapEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-tracking_select".
 */
export interface SettingsTrackingSelect<T extends boolean = true> {
  ga4MeasurementId?: T;
  metaPixelId?: T;
  otherScripts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-integrations_select".
 */
export interface SettingsIntegrationsSelect<T extends boolean = true> {
  zendesk?:
    | T
    | {
        inboundEmail?: T;
        webhookUrl?: T;
      };
  prevo?:
    | T
    | {
        apiUrl?: T;
        apiKey?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-brand_select".
 */
export interface SettingsBrandSelect<T extends boolean = true> {
  header?:
    | T
    | {
        menuItems?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  footer?:
    | T
    | {
        logoText?: T;
        text?: T;
        links?: T;
      };
  brand?:
    | T
    | {
        name?: T;
        locations?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}